dist: trusty

sudo: false

language: node_js

node_js:
 - 6.11.1 # runtime used within Firebase functions

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod

cache:
  bundler: true
  directories:
    - node_modules # NPM packages

install:
  - npm set progress=false
  - npm i
  - npm i -g firebase-ci

script:
  - firebase-ci createConfig
  - npm run lint
  - npm run test
  - npm run build

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: "wp-plugin/brew_tech_graph.zip"
  skip_cleanup: true
  on:
    tags: true
